Mornin_translation_app:
    resource: "@MorninTranslationBundle/Resources/config/routing/app.yml"

Mornin_translation_api:
    resource: "@MorninTranslationBundle/Resources/config/routing/api.yml"
    prefix: /api

Mornin_translation_twig:
    resource: "@MorninTranslationBundle/Resources/config/routing/twig.yml"
    prefix: /twig