Mornin_translation_list:
    path:     /translations
    defaults: { _controller: "MorninTranslationBundle:Rest:list" }
    methods:  [GET]

Mornin_translation_profiler:
    path:         /translations/profiler/{token}
    defaults:     { _controller: "MorninTranslationBundle:Rest:listByProfile" }
    requirements: { _method: GET }

Mornin_translation_update:
    path:     /translations/{id}
    defaults: { _controller: "MorninTranslationBundle:Rest:update" }
    methods:  [PUT]
