mornin_translation_list:
    path:     /translations
    defaults: { _controller: "MorninTranslationBundle:Rest:list" }
    methods:  [GET]

mornin_translation_profiler:
    path:     /translations/profiler/{token}
    defaults: { _controller: "MorninTranslationBundle:Rest:listByProfile" }
    methods:  [GET]

mornin_translation_update:
    path:     /translations/{id}
    defaults: { _controller: "MorninTranslationBundle:Rest:update" }
    methods:  [PUT]

mornin_translation_delete_locale:
    path:     /translations/{id}/{locale}
    defaults: { _controller: "MorninTranslationBundle:Rest:deleteTranslation" }
    methods:  [DELETE]

mornin_translation_delete:
    path:     /translations/{id}
    defaults: { _controller: "MorninTranslationBundle:Rest:delete" }
    methods:  [DELETE]